### ISSUE TITLE
SME(FT) - LL Edition

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [EzioTheDeadPoet/SME-FT-#11]
**SME(FT) - LL Edition**

I have heard multiple people propose the idea of a SME(FT) - LL Edition, and I really like it, but as of rn I am maintaining this list and [Tales from the Northern Lands](https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/), which really doesn't leave room for me to maintain a SME(FT) - LL Edition, which is why I am asking if someone would want to help make it happen.

I plan to eventually do it, but it will surely take some time until I can. So anyone that would make it happen would really help a lot of people get faster and easier access into the more NSFW focused LL modding scene.

Feel free to discuss any mods you would deem essential to a LL NSFW modsetup below in the comments.

**Comment by NegSpec13** [comment]
Hi Ezio. I'd be interested in helping out on the LL version of SME(FT). 
Your modlist has become the basis of my last couple of LO's so doing something like this  to help out would be great.

Cheers

**Comment by EzioTheDeadPoet** [comment]
@NegSpec13 I hope this doesn't sound rude, how much do you know about maintaining a WJ list, or to what extend do you want to help ? 

- do you want to maintain a "fork" of my modlist (I can give you some help getting started) 
  - Here are the official [wabbajack instructions](https://github.com/wabbajack-tools/wabbajack#creating-your-own-modlist) how to make a list
  - If you want to create it hit me up how with a list of mods you would say are essentials, since I would want it to keep that minimal feel. (Best would be here so others can discuss it as well.)
- or do you want to help put together a list of LL mods you will literally find in any NSFW LL setup ?

Luca

**Comment by EzioTheDeadPoet** [comment]
Also have you already joined the WJ discord ?

**Comment by NegSpec13** [comment]
I have joined the discord under the name MikaelH.
I imagine the best thing would be for me to maintain a fork with some essential mods since I haven't really done this before. 
Possibly it might be better to hang out on the discord and I could get some tips from you first.
Thanks

**Comment by umitseyhan75** [comment]
Is this idea completely abandoned or are you still thinking about making it someday?

**Comment by EzioTheDeadPoet** [comment]
I abandoned the idea for the following reasons:

- there are now two very viable NSFW cores and I had to choose one. (which would lead to backlash either way and both would be to much work.)
- I don't have much time for SMEFT itself anymore let alone an alternative version of it.
