### ISSUE TITLE
Include fix for western watchtower texture mismatch

### ISSUE THREAD

**Issue by iarna** [EzioTheDeadPoet/SME-FT-#13]
The bug is that the western watchtower, before the dragon attacks, has a mismatched texture, with the top half being different than the bottom. This is subtle but visible with default textures (the bottom is mossy and slightly darker) and can really stand out with custom textures.

The fix for it is the [Whiterun Tower fix](https://www.nexusmods.com/skyrimspecialedition/mods/14365?tab=files) that's in the optional section of Underground. Despite being the optional section of this other mod, it is an independent fix that works on vanilla assets, and works great on its own.

**Comment by EzioTheDeadPoet** [comment]
wow I am sorry I completely forgot this in the last update. Let's hope I don't forget it with the next one. 😅

**Comment by EzioTheDeadPoet** [comment]
Will be pushed with the next update today. 👍
