### ISSUE TITLE
UltraWide Support

### ISSUE THREAD

**Issue by Jaw-Ahm** [EzioTheDeadPoet/SME-FT-#15]
**Request**
Elysium has a great section for UltraWide support, I can add this in the readme as a pull request, but I am unsure if this would be within the intended scope of this mod. Alternatively, I could link to the Elysium guide, but I don't think this would be optimal.
**Additional context**
I propose adding an UltraWide section to the readme with steps explaining installing these mods:
- Main File: Complete Widescreen Fix for SkyUI 5.2 SE Alpha - 2560x1080
  - Optional Files: Better Dialogue Control Widescreen Fix
  - Optional Files: Better MessageBox Control Widescreen Fix
  - Optional Files: Opt. 1 - Wider MCM Menu for SkyUI - Widescreen Fix
  - Optional Files: Race Menu SE - WIdescreen Fix

**Comment by EzioTheDeadPoet** [comment]
Feel free to make a pull request with a section for this. (can look at where to put it and stuff once I got time) 👍

**Comment by EzioTheDeadPoet** [comment]
Thx for the interest and help :+1:
