### ISSUE TITLE
Add No silly physics damage

### ISSUE THREAD

**Issue by zhongjiedong** [EzioTheDeadPoet/SME-FT-#17]
**Request**
Add the no silly physics damage mod. 

**Additional context**

As far as I can tell this has no adverse effects on the game and even retains rolling rock damage but prevents players from taking damage from walking over collidable objects.

https://www.nexusmods.com/skyrimspecialedition/mods/36132

**Comment by EzioTheDeadPoet** [comment]
will be pushed with the next update today
