### ISSUE TITLE
Update SSELodGen to 4.x Releases

### ISSUE THREAD

**Issue by ghost** [EzioTheDeadPoet/SME-FT-#22]
Request
---------
Replace the `3.2.1` version of SSELodGen with `4.x` beta versions.

The Phoenix Flavour Instructions and Details: https://thephoenixflavour.com/skyrim-se/finalisation/occlusion/#sselodgen
Direct Link on the STEP Forums: https://stepmodifications.org/forum/topic/13451-xlodgen-terrain-lod-beta-73-for-fnv-fo3-fo4-fo4vr-tes5-sse-tes5vr-enderal/

Additional context
--------------------
It improves load order parsing issues due to being based on xEdit 4.x. It also includes the ability to generate Occlusion data in the worldspace to limit how much the game renders regarding invisible objects https://stepmodifications.org/forum/topic/14250-skyrim-tvdt-occlusion-culling-data/.

**Comment by EzioTheDeadPoet** [comment]
included in version 21.04.04 released today
