### ISSUE TITLE
Xbox Controller not working with SMEFT

### ISSUE THREAD

**Issue by jd03asdf** [EzioTheDeadPoet/SME-FT-#27]
The game does not recognize that there is a gamepad hooked up when launching from SMEFT. I get the steam popup that a gamepad is recognized when launching but it doesn't actually connect to the game, stuck with the mouse cursor.

Works fine launching vanilla and tried with The Phoenix Project as well and did not have this issue.... Do you know what mod might be causing this? I tried disabling hanks gamepad fixes as well as the keyboard shortcuts and some dialogue controls but nothing worked :/

**Comment by jd03asdf** [comment]
EDIT**

Looks like the default INI for SMEFT has bGamepadEnable=0 which disbales controller support. Has to be set to "...=1" and now the controller works no problem. If anyone else runs into this issue you just need to change it in the INI editor for whatever profile you're using on the skyrimprefs.ini under [MAIN]

Link for clarification: https://stepmodifications.org/wiki/Guide:SSE_SkyrimPrefs_INI/MAIN

**Comment by EzioTheDeadPoet** [comment]
oh I must have forgotten about that thx.

**Comment by EzioTheDeadPoet** [comment]
fixed
