### ISSUE TITLE
xLODGen.83.7z file does not download because link is broken

### ISSUE THREAD

**Issue by kostum123** [EzioTheDeadPoet/SME-FT-#29]
Wabbajack fails to install mod list with error as below. List needs updating.

1070,82 - Unable to download xLODGen.83.7z (MegaDownloader+State|https://mega.nz/file/EcJhgKpY#4Q86Rd1hUepjm233r8Q_7x3fTWx9axJN2CUc8FXrBsg)
1070,82 - Cannot continue, was unable to download one or more archives

**Comment by EzioTheDeadPoet** [comment]
https://github.com/tr4wzified/SMEFT  moved maintainer.

But he knows.

To get the file until an update is ready go to the Wabbajack discord and go to the `#wabbajack-help` channel in the pins there is the file to download.

**Comment by kostum123** [comment]
> https://github.com/tr4wzified/SMEFT moved maintainer.
> 
> But he knows.
> 
> To get the file until an update is ready go to the Wabbajack discord and go to the `#wabbajack-help` channel in the pins there is the file to download.

I hadn't noticed that the maintainer had changed. Thanks for your quick and helpful reply. As you said, I will get the file from discord until the list is updated.
