### ISSUE TITLE
 Unable to download xLODGen.83.7z, Whole Process Halts

### ISSUE THREAD

**Issue by EP1CN3SS2** [EzioTheDeadPoet/SME-FT-#30]
Really? One removed link puts a halt to the entire process? What kind of incompetency is this? I even downloaded the file from somewhere else, put it in the downloads folder and it still gives the same error/fails. Why even put a mega link into the modlist, who needs xLODGen, thats an advanced process that I could do myself if I wanted to. I wanted patches and a baseline for modding, LODs are not baseline, its extra.

**Comment by EzioTheDeadPoet** [comment]
Get some manners. And think before writing comments.

The list has "Fixes & **Tools**" in it's title.

If you need help with getting that file read the already closed issues.
