### ISSUE TITLE
SME(FT) Current Version 7 Zip Link is broken it directs to an xml page and you must use an earlier version

### ISSUE THREAD

**Issue by Kahn13** [EzioTheDeadPoet/SME-FT-#4]
It's all in the title.

**Comment by EzioTheDeadPoet** [comment]
Try the actual latest version which is v20.04.27 in the releases Tab. When I tried downloading the SMEFT.7z of that release it worked for me.

**Comment by EzioTheDeadPoet** [comment]
But maybe GitHub didn't like me changing the way I do version numbers since after the release of WJ 2.0, WJ has an way to integrate version numbers for lists, but wouldn't allow the long numbers I used with WJ 1.x versions.

**Comment by Kahn13** [comment]
Got it and it's working now, thanks

**Comment by EzioTheDeadPoet** [comment]
Good to hear :D
